### ISSUE TITLE
All of my options are unclickable.

### ISSUE THREAD

**Issue by zlddev** [LIPtoH/TS-SE-Tool#52]
Everything on my screen is greyed out and unusable. I've disabled steam cloud and don't know what I can do to get it working, I just want to remove my £10M debt haha

**Comment by zlddev** [comment]
Thank you for not responding and instead closing it, great support

**Comment by LIPtoH** [comment]
@puppypvp The discussion was closed as enough time had passed and It was not entirely clear what is required from me and my program.
From the description and in the absence of screenshots, it seems that the problem is with the game or the place where documents are stored, and not with the program.
If the program does not have [L] profiles in the drop-down list, then it did not find them in the default path in user's Documents because they were not created by the game or are stored elsewhere (for example, you can start the game with commands to change storage location)

Do you need instructions on how to disable Steam Cloud for a profile? How and where to check if the profile has been transferred?
